apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: quiz
  name: quiz
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quiz
        version: V1.0.4
    spec:
      containers:
      - image: cpruvost/cn-quiz-service:1.0.4-SNAPSHOT
        imagePullPolicy: Always
        name: cn-quiz-service
        env:      
        - name: SPRING_PROFILE
          value: prod
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: url      
        readinessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: quiz
  name: quiz-risky
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quiz
        version: V1.2.0
    spec:
      containers:
      - image: cpruvost/cn-quiz-service:1.2.0-SNAPSHOT
        imagePullPolicy: Always
        name: cn-quiz-service
        env:      
        - name: SPRING_PROFILE
          value: prod
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: url      
        readinessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/liveness
      restartPolicy: Always      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quiz
  name: quiz
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: quiz
  sessionAffinity: None
  type: LoadBalancer