spring:
  application:
    name: quiz-service  

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    #type: oracle.ucp.jdbc.PoolDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: ALTER SESSION SET EDITION=V1
      connection-test-query: select * from dual
      minimum-idle: 5
      maximum-pool-size: 10
    #oracleucp:
     # connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
     # s-q-l-for-validate-connection: select * from dual
     # connection-pool-name: connectionPoolCN
     # initial-pool-size: 5
     # min-pool-size: 3
     # max-pool-size: 10
    #tomcat:  
      #init-s-q-l: ALTER SESSION SET EDITION=V1
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        '[show_sql]': false
        '[use_sql_comments]': true
        '[format_sql]': true
    
  sql:
    init: 
      encoding: UTF-8
      
  config:
    activate:
      on-profile: prod

server:
  port: 8000 

logging:
  level:
    #root: ERROR
    '[oracle.ucp]': INFO
    '[org.springframework.web]': ERROR
    '[com.quizforevent.microservices.quizservice]': INFO
    '[org.hibernate]': ERROR
 