name: Build and Push Docker Images

on: 
  push:
    branches:
      - main
      - develop
  issues:
    types: [opened, reopened]    
  workflow_dispatch:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    name: Docker Build Push
    
    strategy:
      matrix:
        maven: [ '3.8.6' ]
    
    env:
      OCI_CLI_USER: ${{ secrets.TF_VAR_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.TF_VAR_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.TF_VAR_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.TF_VAR_PRIVATE_KEY }}
      OCI_CLI_REGION: ${{ secrets.TF_VAR_REGION }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
       
      - name: Checkout v1.0.4
        run: git checkout tags/v1.0.4 -b main  
      
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: 17
          maven-version: ${{ matrix.maven }}

      - name: Build Docker Image with Maven
        run: |
          mvn -v
          docker -v
          mvn spring-boot:build-image -DskipTests
          docker images
      
      
    
#      - name: Get or create an OCIR Repository
#        uses: oracle-actions/get-ocir-repository@v1.1
#        id: get-ocir-repository
#        with:
#          name: oraclelinux
#          compartment: ${{ secrets.TF_VAR_COMPARTMENT_OCID }}
#
#      - name: Log into OCIR
#        uses: oracle-actions/login-ocir@v1.1
#        id: login-ocir
#        with:
#          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
#
#      - name: Tag and push a container image
#        id: tag-and-push-image
#        run: |
#          docker -v
#          echo "repo : ${{ steps.get-ocir-repository.outputs.repo_path }}"
#          docker pull oraclelinux:8-slim
#          docker tag "oraclelinux:8-slim" "${{ steps.get-ocir-repository.outputs.repo_path }}:8-slim"
#          docker push "${{ steps.get-ocir-repository.outputs.repo_path }}:8-slim"